---
- name: Run a command under PowerShell
  win_shell: Get-Service -Name TapiSrv  | Stop-Service

- name: Run a command under cmd
  win_shell: mkdir C:\temp
  args:
    executable: cmd.exe

- name: Run a multiple shell commands
  win_shell: |
    New-Item -Path C:\temp -ItemType Directory
    Remove-Item -Path C:\temp -Force -Recurse
    New-Item -Path C:\temp -ItemType Directory
    $path_info = Get-Item -Path C:\temp
    $path_info.FullName
- name: Run an executable using win_command
  win_command: whoami.exe

- name: Run a cmd command
  win_command: cmd.exe /c mkdir C:\tmp
