---
- name: Ensure Notepad++ is installed using chocolatey
  win_chocolatey:
    name: notepadplusplus
    state: present
    
- name: Ensure 7zip is installed using chocolatey
  win_chocolatey:
    name: 7zip.install
    state: present
    
- name: Create localadmin user and place in Administrators group
  win_user:
   name: localadmin
   password: "Fontijne123"
   groups: ["Administrators"]

